baseURL = "https://eveningcafe.github.io/po"
languageCode = "en-us"
title = "Swim On!"
theme = "cuisine-book"
enableGitInfo = true

[params]
  author = "Ngo Quang Hoa"
  description = "Swim like a fish"
  logo = "swimming.png"
  comment = true
