baseURL = "https://eveningcafe.github.io/po"
languageCode = "en-us"
title = "Măm Măm"
theme = "cuisine-book"
enableGitInfo = true

[params]
  author = "Kien Nguyen Tuan"
  description = "Măm Măm"
  logo = "SeekPng.com_doughnut-png_4429089.png"
  comment = true
